/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Requisicao_de_itemTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Requisicao_de_itemTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Requisicao_de_item__c());
    }
}