@isTest(seeAllData=true)
public class GeraOTsTest {
    @isTest
    private static void teste1(){
        GeraOTs.gerar('001i00000085QYbAAM','001i00000085QYbAAM', 'INTERNO', '003i000000gl2NCAAY', 'RENNAN SANTOS', '0036e00004KV4J7AAL' , 'AGUARDANDO ATENDIMENTO', '01231000000tb5g', 'AVULSO', 'CALIBRAÇÃO', 'HOSPCOM', 'SK20601437,SK11005793', 'a1Y6e00000C3V6IEAV','itens', 'Problema', system.NOW(), system.NOW() );

    }
}